/*
 * This file was generated by the Gradle 'init' task.
 *
 * This settings file is used to specify which projects to include in your build-logic build.
 * This project uses @Incubating APIs which are subject to change.
 */

rootProject.name = "matching_engine-build-logic"

/* vim: set ts=2 sw=2 sts=2 expandtab ff=unix fenc=utf-8 */
