/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
  id("matching_engine.java-library-conventions")
}
/* vim: set ts=2 sw=2 sts=2 expandtab ff=unix fenc=utf-8 */
